bug fix

diff --git a/.github/workflows/template.yml b/.github/workflows/template.yml
--- a/.github/workflows/template.yml
+++ b/.github/workflows/template.yml
@@ -1,66 +1,66 @@
-# name: GameCI Template 🎮
+name: GameCI Template 🎮
 
-# on: push
+on: push
 
-# env:
-#   UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
+env:
+  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
 
-# jobs:
-#   checkLicense:
-#     name: Check for Unity license
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Fail - No license
-#         if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
-#         run: exit 1
+jobs:
+  checkLicense:
+    name: Check for Unity license
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail - No license
+        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
+        run: exit 1
 
-#   testRunner:
-#     name: Test in ${{ matrix.testMode }} ✨
-#     runs-on: ubuntu-latest
-#     strategy:
-#       fail-fast: false
-#       matrix:
-#         testMode:
-#           - EditMode
-#           - PlayMode #Running on both modes at once (Easy for future use)
-#     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v2
+  testRunner:
+    name: Test in ${{ matrix.testMode }} ✨
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        testMode:
+          - EditMode
+          - PlayMode #Running on both modes at once (Easy for future use)
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-#       - name: Create LFS file list
-#         run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id #Caching large files in the project..no need to download again when re run
+      - name: Create LFS file list
+        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id #Caching large files in the project..no need to download again when re run
 
-#       - name: Restore LFS cache #Cashing speeds up the tests
-#         uses: actions/cache@v2
-#         id: lfs-cache
-#         with:
-#           path: .git/lfs
-#           key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
+      - name: Restore LFS cache #Cashing speeds up the tests
+        uses: actions/cache@v2
+        id: lfs-cache
+        with:
+          path: .git/lfs
+          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
 
-#       - name: Git LFS Pull
-#         run: |
-#           git lfs pull
-#           git add .
-#           git reset --hard
-#       - name: Restore Library cache #caching the library..all unity editor files..speeds up the build
-#         uses: actions/cache@v2
-#         with:
-#           path: Library
-#           key: Library-test-project-${{ matrix.targetPlatform }}
-#           restore-keys: |
-#             Library-test-project-
-#             Library-
-#       - uses: game-ci/unity-test-runner@v2.0-alpha-5
-#         id: testRunner #testing using all modes
-#         with:
-#           testMode: ${{ matrix.testMode }}
-#           checkName: ${{ matrix.testMode }} test results
-#           githubToken: ${{ secrets.GITHUB_TOKEN }}
+      - name: Git LFS Pull
+        run: |
+          git lfs pull
+          git add .
+          git reset --hard
+      - name: Restore Library cache #caching the library..all unity editor files..speeds up the build
+        uses: actions/cache@v2
+        with:
+          path: Library
+          key: Library-test-project-${{ matrix.targetPlatform }}
+          restore-keys: |
+            Library-test-project-
+            Library-
+      - uses: game-ci/unity-test-runner@v2.0-alpha-5
+        id: testRunner #testing using all modes
+        with:
+          testMode: ${{ matrix.testMode }}
+          checkName: ${{ matrix.testMode }} test results
+          githubToken: ${{ secrets.GITHUB_TOKEN }}
 
-#       - uses: actions/upload-artifact@v2 #uploads the results of the test to view if there are failures
-#         with:
-#           name: Test results (${{ matrix.testMode }})
-#           path: ${{ steps.testRunner.outputs.artifactsPath }}
+      - uses: actions/upload-artifact@v2 #uploads the results of the test to view if there are failures
+        with:
+          name: Test results (${{ matrix.testMode }})
+          path: ${{ steps.testRunner.outputs.artifactsPath }}
 
 #   buildWebGL:
 #     # needs: testRunner #Build only if all tests are passed
@@ -124,121 +124,121 @@
 #           folder: build/WebGL
 
 
-name: Test, Build, and Deploy with GameCI
-on:
-  push:
-    branches:
-      - develop
-    paths:
-      - 'Assets/**'
-      - 'Packages/**'
-      - 'ProjectSettings/**'
-  pull_request:
-    types:
-      - opened
-    branches:    
-      - develop
-      - main
-    paths:
-      - 'Assets/**'
-      - 'Packages/**'
-      - 'ProjectSettings/**'
-  release:
-    types:
-      - published
-  workflow_dispatch:
-    inputs:
-      workflow_mode:
-        description: '[release] [Android, iOS, StandaloneLinux64, WebGL, StandaloneWindows, StandaloneWindows64, WSAPlayer, StandaloneOSX, Steam]'
-        required: false
-        default: ''
+# name: Test, Build, and Deploy with GameCI
+# on:
+#   push:
+#     branches:
+#       - develop
+#     paths:
+#       - 'Assets/**'
+#       - 'Packages/**'
+#       - 'ProjectSettings/**'
+#   pull_request:
+#     types:
+#       - opened
+#     branches:    
+#       - develop
+#       - main
+#     paths:
+#       - 'Assets/**'
+#       - 'Packages/**'
+#       - 'ProjectSettings/**'
+#   release:
+#     types:
+#       - published
+#   workflow_dispatch:
+#     inputs:
+#       workflow_mode:
+#         description: '[release] [Android, iOS, StandaloneLinux64, WebGL, StandaloneWindows, StandaloneWindows64, WSAPlayer, StandaloneOSX, Steam]'
+#         required: false
+#         default: ''
 
 
-jobs:
+# jobs:
 
-  tests:
-    name: Test Code Quality
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-          lfs: true
-      - name: Cache Library
-        uses: actions/cache@v2
-        with:
-          path: Library
-          key: Library-test-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
-          restore-keys: Library-test-
-      - name: Setup dotnet for SonarQube
-        uses: actions/setup-dotnet@v2
-        with:
-          dotnet-version: '5.0.x'
-      - name: Set up JDK 11 for SonarQube
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'zulu'
-          java-version: 11
-      - name: Setup Unity for SonarQube
-        id: setup-unity
-        uses: kuler90/setup-unity@v1
-      - name: Activate Unity for SonarQube
-        uses: kuler90/activate-unity@v1
-        with:
-          unity-username: ${{ secrets.UNITY_EMAIL }}
-          unity-password: ${{ secrets.UNITY_PASSWORD }}
-          unity-serial: ${{ secrets.UNITY_SERIAL }}
-      - name: Generate Solution for SonarQube
-        run: xvfb-run -ae /dev/stdout ${{ steps.setup-unity.outputs.unity-path }} -batchmode -logFile /dev/stdout -quit -customBuildName Card-Game-Simulator -projectPath . -executeMethod  UnityEditor.SyncVS.SyncSolution
-      - name: Run Unit Tests
-        uses: game-ci/unity-test-runner@main
-        env:
-          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
-          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
-          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
-        with:
-          customParameters: -enableCodeCoverage -coverageResultsPath artifacts -debugCodeOptimization
-          githubToken: ${{ secrets.GITHUB_TOKEN }}
-      - name: SonarQube Analysis
-        env:
-          FrameworkPathOverride: ${{ steps.setup-unity.outputs.unity-path }}/../Data/MonoBleedingEdge/
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          pwd; ls -alh
-          sed -i 's/<ReferenceOutputAssembly>false<\/ReferenceOutputAssembly>/<ReferenceOutputAssembly>true<\/ReferenceOutputAssembly>/g' *.csproj
-          sed -i 's/\([A-Za-z0-9.-]\+csproj\)/Card-Game-Simulator\/&/g' Card-Game-Simulator.sln
-          mv Card-Game-Simulator.sln ..
-          cd ..
-          dotnet tool install --global dotnet-sonarscanner
-          dotnet sonarscanner begin \
-            /o:"finol-digital" \
-            /k:"finol-digital_Card-Game-Simulator" \
-            /d:sonar.login="$SONAR_TOKEN" \
-            /d:sonar.host.url=https://sonarcloud.io \
-            /d:sonar.exclusions=Assets/Plugins/**,Assets/Mirror/**, \
-            /d:sonar.cpd.exclusions=Assets/Tests/** \
-            /d:sonar.coverage.exclusions=Assets/Tests/** \
-            /d:sonar.cs.nunit.reportsPaths=Card-Game-Simulator/artifacts/editmode-results.xml,Card-Game-Simulator/artifacts/playmode-results.xml \
-            /d:sonar.cs.opencover.reportsPaths=Card-Game-Simulator/artifacts/Card-Game-Simulator-opencov/EditMode/TestCoverageResults_0000.xml,Card-Game-Simulator/artifacts/Card-Game-Simulator-opencov/PlayMode/TestCoverageResults_0000.xml
-          dotnet build Card-Game-Simulator.sln
-          dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
-          cd Card-Game-Simulator
-      - name: Update Release Notes
-        if: github.event.action == 'published'
-        env:
-          RELEASE_NOTES: ${{ github.event.release.body }}
-        run: |
-          echo "$RELEASE_NOTES" > fastlane/metadata/android/en-US/changelogs/default.txt
-          echo "$RELEASE_NOTES" > fastlane/metadata/en-US/release_notes.txt
-      - name: Auto-Commit Release Notes
-        if: github.event.action == 'published'
-        uses: stefanzweifel/git-auto-commit-action@v4
-        with:
-          branch: main
-          file_pattern: fastlane/metadata
-          commit_message: Update Release Notes
+#   tests:
+#     name: Test Code Quality
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout Repository
+#         uses: actions/checkout@v3
+#         with:
+#           fetch-depth: 0
+#           lfs: true
+#       - name: Cache Library
+#         uses: actions/cache@v2
+#         with:
+#           path: Library
+#           key: Library-test-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
+#           restore-keys: Library-test-
+#       - name: Setup dotnet for SonarQube
+#         uses: actions/setup-dotnet@v2
+#         with:
+#           dotnet-version: '5.0.x'
+#       - name: Set up JDK 11 for SonarQube
+#         uses: actions/setup-java@v3
+#         with:
+#           distribution: 'zulu'
+#           java-version: 11
+#       - name: Setup Unity for SonarQube
+#         id: setup-unity
+#         uses: kuler90/setup-unity@v1
+#       - name: Activate Unity for SonarQube
+#         uses: kuler90/activate-unity@v1
+#         with:
+#           unity-username: ${{ secrets.UNITY_EMAIL }}
+#           unity-password: ${{ secrets.UNITY_PASSWORD }}
+#           unity-serial: ${{ secrets.UNITY_SERIAL }}
+#       - name: Generate Solution for SonarQube
+#         run: xvfb-run -ae /dev/stdout ${{ steps.setup-unity.outputs.unity-path }} -batchmode -logFile /dev/stdout -quit -customBuildName Card-Game-Simulator -projectPath . -executeMethod  UnityEditor.SyncVS.SyncSolution
+#       - name: Run Unit Tests
+#         uses: game-ci/unity-test-runner@main
+#         env:
+#           UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
+#           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
+#           UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
+#         with:
+#           customParameters: -enableCodeCoverage -coverageResultsPath artifacts -debugCodeOptimization
+#           githubToken: ${{ secrets.GITHUB_TOKEN }}
+#       - name: SonarQube Analysis
+#         env:
+#           FrameworkPathOverride: ${{ steps.setup-unity.outputs.unity-path }}/../Data/MonoBleedingEdge/
+#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#         run: |
+#           pwd; ls -alh
+#           sed -i 's/<ReferenceOutputAssembly>false<\/ReferenceOutputAssembly>/<ReferenceOutputAssembly>true<\/ReferenceOutputAssembly>/g' *.csproj
+#           sed -i 's/\([A-Za-z0-9.-]\+csproj\)/Card-Game-Simulator\/&/g' Card-Game-Simulator.sln
+#           mv Card-Game-Simulator.sln ..
+#           cd ..
+#           dotnet tool install --global dotnet-sonarscanner
+#           dotnet sonarscanner begin \
+#             /o:"finol-digital" \
+#             /k:"finol-digital_Card-Game-Simulator" \
+#             /d:sonar.login="$SONAR_TOKEN" \
+#             /d:sonar.host.url=https://sonarcloud.io \
+#             /d:sonar.exclusions=Assets/Plugins/**,Assets/Mirror/**, \
+#             /d:sonar.cpd.exclusions=Assets/Tests/** \
+#             /d:sonar.coverage.exclusions=Assets/Tests/** \
+#             /d:sonar.cs.nunit.reportsPaths=Card-Game-Simulator/artifacts/editmode-results.xml,Card-Game-Simulator/artifacts/playmode-results.xml \
+#             /d:sonar.cs.opencover.reportsPaths=Card-Game-Simulator/artifacts/Card-Game-Simulator-opencov/EditMode/TestCoverageResults_0000.xml,Card-Game-Simulator/artifacts/Card-Game-Simulator-opencov/PlayMode/TestCoverageResults_0000.xml
+#           dotnet build Card-Game-Simulator.sln
+#           dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
+#           cd Card-Game-Simulator
+#       - name: Update Release Notes
+#         if: github.event.action == 'published'
+#         env:
+#           RELEASE_NOTES: ${{ github.event.release.body }}
+#         run: |
+#           echo "$RELEASE_NOTES" > fastlane/metadata/android/en-US/changelogs/default.txt
+#           echo "$RELEASE_NOTES" > fastlane/metadata/en-US/release_notes.txt
+#       - name: Auto-Commit Release Notes
+#         if: github.event.action == 'published'
+#         uses: stefanzweifel/git-auto-commit-action@v4
+#         with:
+#           branch: main
+#           file_pattern: fastlane/metadata
+#           commit_message: Update Release Notes
 
   buildWithLinux:
     name: Build for ${{ matrix.targetPlatform }}
